# Lab 3: Contextual Bandit-Based News Article Recommendation

**`Course`:** Reinforcement Learning Fundamentals  
**`Student Name`:**  Ishita Rathore
**`Roll Number`:**  U20230044
**`GitHub Branch`:** ishita_U20230044

# Imports and Setup

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

from rlcmab_sampler import sampler


# Load Datasets

In [2]:
# Load datasets
news_df = pd.read_csv("data/news_articles.csv")
train_users = pd.read_csv("data/train_users.csv")
test_users = pd.read_csv("data/test_users.csv")

print(news_df.head())
print(train_users.head())


                                                link  \
0  https://www.huffpost.com/entry/covid-boosters-...   
1  https://www.huffpost.com/entry/american-airlin...   
2  https://www.huffpost.com/entry/funniest-tweets...   
3  https://www.huffpost.com/entry/funniest-parent...   
4  https://www.huffpost.com/entry/amy-cooper-lose...   

                                            headline   category  \
0  Over 4 Million Americans Roll Up Sleeves For O...  U.S. NEWS   
1  American Airlines Flyer Charged, Banned For Li...  U.S. NEWS   
2  23 Of The Funniest Tweets About Cats And Dogs ...     COMEDY   
3  The Funniest Tweets From Parents This Week (Se...  PARENTING   
4  Woman Who Called Cops On Black Bird-Watcher Lo...  U.S. NEWS   

                                   short_description               authors  \
0  Health experts said it is too early to predict...  Carla K. Johnson, AP   
1  He was subdued by passengers and crew when he ...        Mary Papenfuss   
2  "Until you have a dog y

## Data Preprocessing

In this section:
- Handle missing values
- Encode categorical features
- Prepare data for user classification

In [3]:
print("News duplicates:", news_df.duplicated().sum())
print("Train users duplicates:", train_users.duplicated().sum())
print("Test users duplicates:", test_users.duplicated().sum())
print("News nulls:", news_df.isnull().sum())
print("Train users nulls:", train_users.isnull().sum())
print("Test users nulls:", test_users.isnull().sum())

News duplicates: 13
Train users duplicates: 0
Test users duplicates: 0
News nulls: link                     0
headline                 6
category                 0
short_description    19712
authors              37418
date                     0
dtype: int64
Train users nulls: user_id                          0
age                            698
income                           0
clicks                           0
purchase_amount                  0
session_duration                 0
content_variety                  0
engagement_score                 0
num_transactions                 0
avg_monthly_spend                0
avg_cart_value                   0
browsing_depth                   0
revisit_rate                     0
scroll_activity                  0
time_on_site                     0
interaction_count                0
preferred_price_range            0
discount_usage_rate              0
wishlist_size                    0
product_views                    0
repeat_purchase_gap (da

In [4]:
from sklearn.impute import SimpleImputer


num_cols = train_users.select_dtypes(include=['int64', 'float64']).columns
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
train_users[num_cols] = imputer.fit_transform(train_users[num_cols])
train_users['subscriber'] = train_users['subscriber'].astype(int)
train_users = train_users.drop(columns=['browser_version', 'region_code', 'user_id'])

In [5]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# train test dfs
X_users = train_users.drop(columns=['label'])
y_users = train_users['label']

encoder = LabelEncoder()
y_users = encoder.fit_transform(y_users)

scaler = StandardScaler()
X_users = scaler.fit_transform(X_users)

print("x_users;", X_users[:5])
print("y_users;", y_users[:5])

# news df
news_df = news_df.dropna(subset=['category'])
categories = news_df["category"].unique()
arms = {cat: i for i, cat in enumerate(categories)}
print("Arms mapping:", arms)

x_users; [[-1.60854271e-02  2.20907469e-01 -1.59472128e-01 -4.25788002e-01
  -6.72161351e-01 -5.10517755e-01 -4.89355638e-01 -1.17893364e+00
  -4.15620459e-01 -2.78104076e-01 -5.13933330e-01 -6.82975577e-01
  -5.66027245e-01 -5.84266582e-01  4.10286736e-01 -6.18276832e-01
   3.37140316e-01 -1.30614404e-03 -5.62355332e-01  7.33123871e-01
   2.96085692e-01 -6.44160503e-01  8.55123589e-01 -1.77700391e+00
   1.28836329e+00  1.57255018e-01  8.96136086e-01 -8.92810306e-01
  -6.20517164e-01]
 [ 1.83156498e+00 -1.96686850e-01  1.43706822e-01  7.00719320e-02
  -4.57787134e-01  5.01071763e-01  4.08397947e-01 -3.97924273e-01
  -5.17823809e-01  8.91122791e-02 -4.35655464e-01  1.33702265e+00
  -4.79205482e-01 -8.11667697e-02 -7.57290770e-01  8.89815635e-02
   6.09543584e-01  3.71877866e-01  9.00141720e-01 -3.73661559e-01
  -3.01484821e-01  1.24272136e+00  1.30893858e+00  4.25341496e-01
  -2.31704290e-02 -4.21420301e-01 -1.56122896e+00 -1.10905913e+00
   1.61155897e+00]
 [-1.60854271e-02 -1.13634827

## User Classification

Train a classifier to predict the user category (`User1`, `User2`, `User3`),
which serves as the **context** for the contextual bandit.


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_users, y_users, test_size=0.2, random_state=44)

In [7]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()
clf.fit(X_train, y_train)

RandomForestClassifier()

In [8]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8025
              precision    recall  f1-score   support

           0       0.83      0.78      0.81       158
           1       0.84      0.88      0.86       128
           2       0.72      0.74      0.73       114

    accuracy                           0.80       400
   macro avg       0.80      0.80      0.80       400
weighted avg       0.80      0.80      0.80       400

[[124   4  30]
 [ 13 113   2]
 [ 12  18  84]]


# `Contextual Bandit`

## Reward Sampler Initialization

The sampler is initialized using the student's roll number `i`.
Rewards are obtained using `sampler.sample(j)`.


## Arm Mapping

| Arm Index (j) | News Category | User Context |
|--------------|---------------|--------------|
| 0–3          | Entertainment, Education, Tech, Crime | User1 |
| 4–7          | Entertainment, Education, Tech, Crime | User2 |
| 8–11         | Entertainment, Education, Tech, Crime | User3 |

## Epsilon-Greedy Strategy

This section implements the epsilon-greedy contextual bandit algorithm.


## Upper Confidence Bound (UCB)

This section implements the UCB strategy for contextual bandits.

## SoftMax Strategy

This section implements the SoftMax strategy with temperature $ \tau = 1$.


## Reinforcement Learning Simulation

We simulate the bandit algorithms for $T = 10,000$ steps and record rewards.

P.S.: Change $T$ value as and if required.


## Results and Analysis

This section presents:
- Average Reward vs Time
- Hyperparameter comparisons
- Observations and discussion


## Final Observations

- Comparison of Epsilon-Greedy, UCB, and SoftMax
- Effect of hyperparameters
- Strengths and limitations of each approach
